# Site settings
title: Juntaek's Blog
header-img: img/home-bg.jpg
email: juntaek.lee@nhnent.com
copyright_name: Juntaek's Blog/NHN Ent.
description: "This is JuntaekLee's Blog."
baseurl: ""
url: ""
twitter_username: ljt629
github_username:  ljt629
facebook_username:  ljt629@naver.com
email_username:  juntaek.lee@nhnent.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
